### ISSUE TITLE
channelMap is missing

### ISSUE THREAD

**Issue by nicksp** [x-team/strapi-provider-email-multi#1]
It looks like `channelMap` definition is missing https://github.com/x-team/strapi-provider-email-multi/blob/1710261e4c65252f47bd4e56e763da2c7790599e/index.js#L10

**Comment by joshwnj** [comment]
Ah thanks @nicksp, I had missed that :)  It was part of the original implementation but then I refactored so that this wasn't needed anymore. However I forgot to delete the old function.  Done now in #2.
